import streamlit as st

st.title("Titulo Principal", anchor='titulo', help='Topo')

st.title("_italico_, negrito :red[vermelho] :sunglasses:")

st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.title("Titulo Meio :boom: :wave:", anchor='meio', help='Topo')
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()
st.divider()

st.page_link('http://localhost:8501#titulo', label='Topo', )
st.page_link('http://localhost:8501#meio', label='Meio', )